# Generated by Django 3.1.1 on 2020-12-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pofile',
            old_name='user',
            new_name='userpro',
        ),
    ]
